Repository SallyHaefling/sticky-dos-ui, pull requests merged in 2019-05, with the labels that each got.

#17 Add componentDidMount and postTest function
  src/containers/App/index.js
Labels: good first issue

#18 Init structure
  src/components/DisplayField/index.js
  src/components/Header/index.js
  src/containers/App/index.js
  src/containers/Card/index.js
Labels: good first issue

#24 Build form
  src/components/Header/index.js
  src/containers/App/_App.scss
  src/containers/Form/index.js
Labels: Essential, good first issue

#26 Start router implementation
  src/containers/App/index.js
  src/containers/Form/index.js
Labels: Essential

#27 Route start
  src/components/CardDetails/index.js
  src/containers/App/index.js
  src/containers/Card/index.js
Labels: Essential

#29 Post correct info to server
  public/index.html
  src/components/Header/index.js
  src/containers/App/_App.scss
  src/containers/Form/index.js
Labels: Essential, good first issue

#30 Testing
  src/actions/actions.spec.js
  src/components/CardDetails/index.js
  src/components/DisplayField/index.js
  src/containers/App/_App.scss
  src/containers/App/index.js
  src/containers/Card/index.js
  src/containers/Form/Form.spec.js
  src/containers/Form/__snapshots__/Form.spec.js.snap
  src/containers/Form/index.js
  src/reducers/cardList.spec.js
Labels: Essential

#31 Breakout fetch
  src/containers/App/index.js
  src/containers/Form/index.js
  src/utils/apicalls.js
  src/utils/apicalls.test.js
Labels: enhancement

#32 Post new card
  src/components/Header/_Header.scss
  src/components/Header/index.js
  src/containers/Card/index.js
  src/containers/Form/index.js
  src/imgs/Sticky-Note.svg
  src/index.scss
Labels: enhancement, good first issue

#38 New list item
  src/components/Header/index.js
  src/containers/App/_App.scss
  src/containers/App/index.js
  src/containers/Card/index.js
  src/containers/Form/_Form.scss
  src/containers/Form/index.js
  src/index.scss
Labels: Essential, enhancement, good first issue

#40 Merge work
  src/components/CardDetails/index.js
  src/components/DisplayField/index.js
  src/components/Header/index.js
  src/containers/App/_App.scss
  src/containers/App/index.js
  src/containers/Card/index.js
  src/containers/Form/index.js
Labels: Essential, bug, enhancement

#41 ComponentdidUpdate on newCard, and Redirect from cardDetails
  src/components/CardDetails/index.js
  src/components/DisplayField/index.js
Labels: enhancement, good first issue

#42 Edit details
  src/actions/index.js
  src/components/CardDetails/_CardDetails.scss
  src/components/CardDetails/index.js
  src/components/DisplayField/index.js
  src/containers/App/index.js
  src/containers/Form/index.js
  src/index.scss
  src/reducers/cardList.js
  src/utils/apicalls.js
Labels: Essential, enhancement, good first issue

#43 Style bigCard & smallCard
  src/components/CardDetails/_CardDetails.scss
  src/components/CardDetails/index.js
  src/components/DisplayField/index.js
  src/containers/App/_App.scss
  src/containers/Card/_Card.scss
  src/containers/Card/index.js
  src/containers/Form/_Form.scss
  src/containers/Form/index.js
  src/index.scss
  src/mixins.scss
  src/variables.scss
Labels: enhancement, good first issue, help wanted

#47 Convert lI from state to method
  src/containers/Form/index.js
Labels: Essential, enhancement
